; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24234.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\rocketproductions\AppData\Local\Temp\2\.NETFramework,Version=v4.6.AssemblyAttributes.cpp"
